# Generated by Django 4.2 on 2023-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_market', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
