# Generated by Django 4.2 on 2023-05-02 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman_info',
            name='product',
        ),
        migrations.AddField(
            model_name='item_info',
            name='salesman',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesman_info',
            name='validator_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='data_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesman_info',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesman_info',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='RatingStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_storage', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('unique_user', models.CharField(max_length=100, null=True)),
                ('id_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_market.item_info')),
                ('salesman_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_market.salesman_info')),
            ],
        ),
    ]
