# Generated by Django 4.2 on 2023-05-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0002_remove_salesman_info_product_item_info_salesman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_salesman', models.CharField(max_length=100, null=True)),
                ('added_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_market.item_info')),
            ],
        ),
    ]
