# Generated by Django 4.2 on 2023-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0003_basketscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='imagine_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
