# Generated by Django 4.2 on 2023-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0004_item_info_imagine_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='imagine_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
