# Generated by Django 4.2 on 2023-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0006_alter_item_info_imagine_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='imagine_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
