# Generated by Django 4.2 on 2023-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0007_item_info_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='product_description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
