# Generated by Django 4.2 on 2023-05-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0008_alter_item_info_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_info',
            name='product_description',
        ),
    ]
