# Generated by Django 4.2 on 2023-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0009_remove_item_info_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='product_description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
