# Generated by Django 4.2 on 2023-05-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0010_item_info_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.TextField()),
                ('comment_user', models.CharField(max_length=100, null=True)),
                ('comment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_market.item_info', to_field='name')),
            ],
        ),
    ]
