# Generated by Django 4.2 on 2023-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0014_alter_usercomments_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='comment_item',
            field=models.CharField(max_length=100),
        ),
    ]
