# Generated by Django 4.2 on 2023-05-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0016_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_item',
        ),
        migrations.AddField(
            model_name='item_info',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_market.category', verbose_name='category'),
        ),
    ]
