# Generated by Django 4.2 on 2023-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0018_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
