# Generated by Django 4.2 on 2023-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0019_alter_item_info_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketscope',
            name='unique_parameter',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
