# Generated by Django 4.2 on 2023-05-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0020_basketscope_unique_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketscope',
            name='unique_parameter',
        ),
    ]
