# Generated by Django 4.2 on 2023-05-16 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0021_remove_basketscope_unique_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman_info',
            name='card_number',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
