# Generated by Django 4.2 on 2023-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0022_salesman_info_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='imagine_file',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='product_description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
