# Generated by Django 4.2 on 2023-06-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0023_alter_item_info_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
