# Generated by Django 4.2 on 2023-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_market', '0024_delete_usercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
